create table member (
    id         bigint generated by default as identity (start with 1) primary key,
    first_name varchar(225),
    last_name  varchar(225),
    email      varchar(225),
    password   varchar(255),
    photo      varchar(45),
    enabled    boolean default false not null,
    createdOn  datetime,
    modifiedOn datetime,
    createdBy  varchar(45),
    modifiedBy varchar(45)
);

create table roles (
    id          bigint generated by default as identity (start with 5) primary key,
    name        varchar(225),
    description varchar(225),
    createdOn   datetime,
    modifiedOn  datetime,
    createdBy   varchar(45),
    modifiedBy  varchar(45)
);

create table users_roles(
    user_id bigint,
    role_id bigint
);

